/* ============================================
   MODULE DATA: Products & Categories Portfolio
   FILE: src/modules/website/products/data.js
   ============================================ */

export const PRODUCTS_PAGE_HEADER = {
  badge: "High-Performance Agrochemicals",
  title: "Complete Crop Protection & Nutrition Solutions",
  subtitle: "Explore our state-of-the-art formulations developed to safeguard crops from damaging pests, blights, and weeds while boosting harvest vigor.",
};

export const PRODUCTS_CATEGORIES_DATA = [
  {
    slug: "insecticides",
    name: "Insecticides",
    description: "Targeted pest control formulated for reliable knockdown without compromising crop safety.",
    shortDesc: "Targeted pest control formulated for reliable knockdown without compromising crop safety.",
    heroImage: "/images/banners/insecticides-hero-banner.png",
    overview: "Redberry insecticides utilize high-purity active ingredients with rapid knock-down action, translaminar penetration, and long-lasting ovicidal and larvicidal effects to protect cotton, paddy, vegetables, and fruit orchards.",
    products: [
      {
        id: "redprid-super",
        name: "Redprid Super",
        technicalName: "Imidacloprid 17.8% SL",
        category: "insecticides",
        tag: "Bestseller",
        image: "/images/products/redprid.jpg",
        description: "Systemic insecticide with translaminar action for controlling sucking pests like aphids, jassids, thrips, and whiteflies.",
        targetPests: ["Aphids", "Jassids", "Thrips", "Whiteflies", "Brown Plant Hopper"],
        targetCrops: ["Cotton", "Paddy", "Chilli", "Sugarcane", "Tomato", "Mango"],
        dosage: "50 - 100 ml per acre (0.5 ml - 1 ml per litre of water)",
        packSizes: ["100 ml", "250 ml", "500 ml", "1 Ltr", "5 Ltr"],
        features: [
          "Rapid absorption through foliage and roots",
          "Excellent rain-fastness within 2 hours of application",
          "Low dosage requirement with prolonged residual control",
        ],
      },
      {
        id: "chlofos-50",
        name: "Chlofos Ultra",
        technicalName: "Chlorpyrifos 50% + Cypermethrin 5% EC",
        category: "insecticides",
        tag: "Dual Action",
        image: "/images/products/chlofos.png",
        description: "Broad-spectrum contact and stomach poison with strong fumigant action against bollworms and chewing caterpillars.",
        targetPests: ["Spotted Bollworm", "Pink Bollworm", "Stem Borer", "Cutworm", "Termites"],
        targetCrops: ["Cotton", "Paddy", "Soybean", "Groundnut", "Vegetables"],
        dosage: "250 - 350 ml per acre",
        packSizes: ["250 ml", "500 ml", "1 Ltr", "5 Ltr"],
        features: [
          "Synergistic dual-active combination for resistant pests",
          "Instant knock-down with rapid flushing action",
          "Effective soil treatment for soil-dwelling insects and termites",
        ],
      },
      {
        id: "chlocyp-forte",
        name: "Chlocyp Forte",
        technicalName: "Cypermethrin 10% EC",
        category: "insecticides",
        tag: "Fast Knockdown",
        image: "/images/products/chlocyp.png",
        description: "Non-systemic pyrethroid insecticide effective against chewing and foliage-eating caterpillars.",
        targetPests: ["Bollworms", "Diamondback Moth", "Fruit Borer", "Shoot Borer"],
        targetCrops: ["Cotton", "Cabbage", "Okra", "Brinjal", "Wheat"],
        dosage: "200 - 300 ml per acre",
        packSizes: ["100 ml", "250 ml", "500 ml", "1 Ltr"],
        features: [
          "Immediate paralytic knockdown of larval pests",
          "High thermal stability in sunny weather",
          "Safe for beneficial soil microflora at recommended rates",
        ],
      },
      {
        id: "redthrina-max",
        name: "Redthrina Max",
        technicalName: "Lambda-Cyhalothrin 4.9% CS",
        category: "insecticides",
        tag: "Capsule Suspension",
        image: "/images/products/redthrina.jpg",
        description: "Micro-encapsulated formulation offering extended protection against leaf folders and borers.",
        targetPests: ["Leaf Folder", "Stem Borer", "Pod Borer", "Thrips"],
        targetCrops: ["Paddy", "Cotton", "Chilli", "Tomato", "Pigeon Pea"],
        dosage: "150 - 200 ml per acre",
        packSizes: ["250 ml", "500 ml", "1 Ltr"],
        features: [
          "Advanced capsule suspension technology for slow release",
          "Superior resistance to UV photo-degradation",
          "High safety index for spray operators",
        ],
      },
    ],
  },
  {
    slug: "fungicides",
    name: "Fungicides",
    description: "Disease management solutions that keep crops healthier through every growth stage.",
    shortDesc: "Disease management solutions that keep crops healthier through every growth stage.",
    heroImage: "/images/banners/tractor_spray_hero.jpg",
    overview: "Redberry fungicides arrest spore germination, stop fungal mycelial growth, and build plant immunity against leaf spots, downy mildew, powdery mildew, and root rots.",
    products: [
      {
        id: "bioforce-shield",
        name: "Bioforce Shield",
        technicalName: "Azoxystrobin 18.2% + Difenoconazole 11.4% SC",
        category: "fungicides",
        tag: "Premium Broad Spectrum",
        image: "/images/products/bioforce.jpg",
        description: "Dual-mode systemic fungicide combining strobilurin and triazole chemistries for curative and preventive defense.",
        targetPests: ["Powdery Mildew", "Anthracnose", "Dieback", "Early & Late Blight", "Rust"],
        targetCrops: ["Chilli", "Tomato", "Cumin", "Grapes", "Paddy", "Maize"],
        dosage: "150 - 200 ml per acre (1 ml per litre)",
        packSizes: ["100 ml", "200 ml", "500 ml", "1 Ltr"],
        features: [
          "Exceptional greening effect and photosynthetic enhancement",
          "Acropetal and translaminar distribution throughout plant tissues",
          "Prevents spore germination and inhibits fungal ergosterol synthesis",
        ],
      },
      {
        id: "redcure-m45",
        name: "Redcure M-45",
        technicalName: "Mancozeb 75% WP",
        category: "fungicides",
        tag: "Contact Defense",
        image: "/images/products/premium_dummy.jpg",
        description: "Multi-site protective contact fungicide providing dependable coverage against fungal and algal blights.",
        targetPests: ["Downy Mildew", "Leaf Spot", "Fruit Rot", "Collar Rot", "Tikka Disease"],
        targetCrops: ["Potato", "Groundnut", "Apple", "Grape", "Paddy", "Onion"],
        dosage: "600 - 800 g per acre (2.5 g per litre)",
        packSizes: ["500 g", "1 kg", "5 kg"],
        features: [
          "Broadest multi-site action prevents pathogen resistance",
          "Provides vital Manganese and Zinc micro-nutrients to crops",
          "Compatible with most standard tank-mix combinations",
        ],
      },
      {
        id: "redtrio-hex",
        name: "Redtrio Hex",
        technicalName: "Hexaconazole 5% SC",
        category: "fungicides",
        tag: "Systemic Triazole",
        image: "/images/products/bioforce.jpg",
        description: "Potent triazole fungicide for effective eradication of sheath blight in paddy and powdery mildews in orchards.",
        targetPests: ["Sheath Blight", "Powdery Mildew", "Scab", "Rust"],
        targetCrops: ["Paddy", "Mango", "Groundnut", "Apple", "Tea"],
        dosage: "200 - 300 ml per acre",
        packSizes: ["250 ml", "500 ml", "1 Ltr", "5 Ltr"],
        features: [
          "Fast systemic translocation with antisporulant action",
          "Improves fruit shine, firmness, and shelf life",
          "Economical per-acre cost with reliable outcomes",
        ],
      },
    ],
  },
  {
    slug: "herbicides",
    name: "Herbicides",
    description: "Weed control built for clean fields and stronger, unobstructed crop growth.",
    shortDesc: "Weed control built for clean fields and stronger, unobstructed crop growth.",
    heroImage: "/images/banners/tractor_spray_hero.jpg",
    overview: "Redberry herbicides target narrow and broadleaf weeds, sedges, and hardy grasses without causing phytotoxicity to the commercial crop.",
    products: [
      {
        id: "aadhira-weed-stop",
        name: "Aadhira Weed-Stop",
        technicalName: "Pendimethalin 38.7% CS",
        category: "herbicides",
        tag: "Pre-Emergence Leader",
        image: "/images/products/aadhira.png",
        description: "Advanced encapsulated pre-emergence herbicide providing season-long weed control at early crop stages.",
        targetPests: ["Echinochloa spp", "Phalaris minor", "Portulaca oleracea", "Amaranthus spp", "Digitaria"],
        targetCrops: ["Cotton", "Soybean", "Groundnut", "Onion", "Chilli", "Garlic"],
        dosage: "600 - 700 ml per acre",
        packSizes: ["500 ml", "1 Ltr", "3.5 Ltr", "5 Ltr"],
        features: [
          "Forms a chemical barrier preventing weed seed germination",
          "Capsule suspension prevents rapid loss by soil volatilization",
          "Gives seedlings a weed-free head-start for first 40 days",
        ],
      },
      {
        id: "bitcoin-clean",
        name: "Bitcoin Clean 71",
        technicalName: "Ammonium Salt of Glyphosate 71% SG",
        category: "herbicides",
        tag: "Non-Selective",
        image: "/images/products/bitcoin.png",
        description: "Soluble granule non-selective systemic herbicide for non-cropped areas, tea plantations, and field bunds.",
        targetPests: ["Cynodon dactylon", "Cyperus rotundus", "Parthenium", "Sorghum halepense"],
        targetCrops: ["Tea", "Non-Crop Land", "Fallow Land", "Bund Weed Eradication"],
        dosage: "100 g per 15 litre water pump (approx 1 kg per acre)",
        packSizes: ["100 g", "500 g", "1 kg"],
        features: [
          "Translocates down to deep rhizomes and tubers",
          "Complete weed root destruction without soil residual toxicity",
          "Easy to dissolve high-potency water-soluble granules",
        ],
      },
      {
        id: "redweed-quiz",
        name: "Redweed Quiz",
        technicalName: "Quizalofop Ethyl 5% EC",
        category: "herbicides",
        tag: "Post-Emergence Grass Specialist",
        image: "/images/products/aadhira.png",
        description: "Selective post-emergence herbicide specifically targeted against narrow-leaf grassy weeds in broadleaf crops.",
        targetPests: ["Echinochloa crusgalli", "Eleusine indica", "Dactyloctenium", "Eragrostis"],
        targetCrops: ["Soybean", "Cotton", "Groundnut", "Blackgram", "Onion"],
        dosage: "300 - 400 ml per acre",
        packSizes: ["250 ml", "500 ml", "1 Ltr"],
        features: [
          "Safe on all dicotyledonous (broadleaf) commercial crops",
          "Weed growth halts within 48 hours of spraying",
          "Fast systemic translocation to the growing meristem points",
        ],
      },
    ],
  },
  {
    slug: "pgr-nutrition",
    name: "PGR & Plant Nutrition",
    description: "Growth regulators and balanced nutrition for stronger roots, better flowering, and higher yield.",
    shortDesc: "Growth regulators and balanced nutrition for stronger roots, better flowering, and higher yield.",
    heroImage: "/images/banners/tractor_spray_hero.jpg",
    overview: "Formulated with naturally active botanical bio-extracts, chelates, and metabolic stimulants to improve flowering, reduce fruit drop, and combat abiotic drought/heat stress.",
    products: [
      {
        id: "red-bloom-gold",
        name: "RedBloom Gold",
        technicalName: "Nitrobenzene 20% w/w & Amino Chelate Complex",
        category: "pgr-nutrition",
        tag: "Flowering Stimulant",
        image: "/images/products/premium_dummy.jpg",
        description: "Organic plant energizer and flowering booster that optimizes hormonal synthesis and prevents flower drop.",
        targetPests: ["Flowering drop", "Poor pollination", "Low fruit set", "Abiotic stress"],
        targetCrops: ["Cotton", "Chilli", "Tomato", "Pomegranate", "Mango", "Pulses", "Vegetables"],
        dosage: "2 - 2.5 ml per litre of water (300 - 400 ml per acre)",
        packSizes: ["250 ml", "500 ml", "1 Ltr", "5 Ltr"],
        features: [
          "Stimulates massive flowering buds and increases female flower ratio",
          "Boosts chlorophyll concentration and active photosynthesis",
          "Increases fruit size, shine, and uniform maturity",
        ],
      },
      {
        id: "red-humic-ultra",
        name: "RedHumic Ultra",
        technicalName: "Potassium Humate 98% + Fulvic Acid Active",
        category: "pgr-nutrition",
        tag: "Soil & Root Conditioner",
        image: "/images/products/bioforce.jpg",
        description: "High-solubility organic soil conditioner that enhances white root development and improves fertilizer uptake efficiency.",
        targetPests: ["Stunted root development", "Nutrient lock-in", "Soil compaction"],
        targetCrops: ["All Agricultural, Horticultural & Plantation Crops"],
        dosage: "500 g - 1 kg per acre (Drip / Drenching / Soil broadcast)",
        packSizes: ["250 g", "500 g", "1 kg"],
        features: [
          "Accelerates proliferation of beneficial soil mycorrhizae",
          "Unlocks unavailable phosphorus and micronutrients in soil",
          "Increases cation exchange capacity (CEC) and moisture retention",
        ],
      },
      {
        id: "red-gib-pro",
        name: "RedGib Pro",
        technicalName: "Gibberellic Acid 0.001% L",
        category: "pgr-nutrition",
        tag: "Cell Elongator",
        image: "/images/products/redprid.jpg",
        description: "Metabolic growth regulator promoting cell elongation, stalk enlargement, and uniform berry expansion.",
        targetPests: ["Small fruit size", "Delayed vegetative growth", "Uneven canopy"],
        targetCrops: ["Grapes", "Sugarcane", "Cotton", "Banana", "Rice"],
        dosage: "180 - 200 ml per acre (1 ml per litre)",
        packSizes: ["250 ml", "500 ml", "1 Ltr"],
        features: [
          "Enhances berry size and prevents cluster tightness in grapes",
          "Lengthens internodes in sugarcane for higher cane weight",
          "Breaks dormancy and boosts vigorous initial tillering",
        ],
      },
    ],
  },
];
